### ISSUE TITLE
Internal User Activation

### ISSUE THREAD

**Issue by IssacSilva** [ReliablePlumbing/reliable-plumbing#3]
When creating a new user (Technician, Supervisor, Administrator, SystemAdmin) there should be NO reason to activate the account via email. 

Only new users outside the reliable network (example: customers) should require email activation.

**Comment by ahmedGomaa90** [comment]
mail activation is more concerned about verifying the email is a real email, admin may make a typo or any other mistakes.
another more important point is to allow technician or other users to set their own password instead of admin setting a password for him/her then he/she should change this password

**Comment by IssacSilva** [comment]
Suggestion:  
When adding "Technicians" can we populate the email field to only support @sdreliableplumbing.com?  

Reliable Plumbing use a standard password - using this standard password will prevent users from logging in to the system - if email was not configured properly.
